### ISSUE TITLE
Actions has succeeded status even if it is failed

### ISSUE THREAD

**Issue by cakeinpanic** [cchantep/probot-jira#78]
Hi!
I have specified jira url with `https://` and it caused action to fail with an error. However status of action was `success`

Please make actions failed if it has internal js errors.

this is the trace:
```
15:25:35.029Z ERROR probot: Cannot read property 'status' of undefined
  TypeError: Cannot read property 'status' of undefined
      at /app/lib/jira/client.js:43:26
      at process._tickCallback (internal/process/next_tick.js:68:7)
15:25:35.313Z  INFO event: Pull request #1 corresponds to JIRA issue 8685 (id=29be9442-a213-4a9d-ac27-caf751d05122)
15:25:35.333Z ERROR probot: Cannot read property 'status' of undefined
  TypeError: Cannot read property 'status' of undefined
      at /app/lib/jira/client.js:27:26
```

**Comment by cchantep** [comment]
Hi, I think that the action status is unchanged, rather than success. Can you provide a link to the PullRequest?
Considering the root cause, it seems that the JIRA API cannot be requested (and the HTTP response is so invalid).

**Comment by cakeinpanic** [comment]
Unfortunately I can't provide a link cause its in private repo
As I see, JIRA API failed because of invalid jira domain value in the yaml – I did not remove `https://`
I just believe that action should have 'failed' status if this happens to notify user
And the best scenario is to have verbose error to let it be debugged more easily
